version: '3'

services:
  # ---------------------------------------------------------
  # Prism
  prism:
    container_name: sample-prism
    image: stoplight/prism:3
    ports:
      - '4011:4010'
    command: mock -h 0.0.0.0 /api/openapi.yaml
    volumes:
      - ../../openapi/build:/api
  # Redoc
  redoc:
    container_name: samples-redoc
    image: redocly/redoc
    environment:
      - SPEC_URL=/api/openapi.yaml
      - PORT=8080
    ports:
      - '18080:8080'
    volumes:
      - ../../openapi/build:/usr/share/nginx/html/api
