openapi: "3.0.0"
info:
  version: 1.0.0
  title: APIドキュメント
servers:
  - url: 'http://localhost:18080'
    description: Local Vue.js Development Mock
  - url: 'http://localhost:8080'
    description: Local Laravel API Server
  - url: 'http://staging-todo/'
    description: staging server
  - url: 'http://production-todo/'
    description: production server
tags:
  - name: Users
    description: ユーザーに関する API
paths:
  "/api/users":
    $ref: "./paths/users.yaml"
  "/api/users/{id}":
    $ref: "./paths/user.yaml"
  "/api/login":
    $ref: "./paths/login.yaml"
components:
  schemas:
    $ref: "./schemas/index.yaml"
